# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('access_code', models.CharField(max_length=8)),
                ('active_session', models.BooleanField(default=False)),
                ('world_time', models.IntegerField(default=0)),
                ('owning_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Campaign')),
                ('owning_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClassCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('selection_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('icon_url', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('selection_order', models.IntegerField()),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.RuleSet')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Statistic')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticInstanceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic_modifiers', models.ManyToManyField(to='rpg.StatisticInstance')),
            ],
        ),
        migrations.AddField(
            model_name='effect',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.RuleSet'),
        ),
        migrations.AddField(
            model_name='effect',
            name='statistic_modifiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rpg.StatisticInstanceSet'),
        ),
        migrations.AddField(
            model_name='classcollection',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.RuleSet'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_effects',
            field=models.ManyToManyField(to='rpg.Effect'),
        ),
        migrations.AddField(
            model_name='class',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.ClassCollection'),
        ),
        migrations.AddField(
            model_name='class',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.RuleSet'),
        ),
        migrations.AddField(
            model_name='class',
            name='statistic_modifiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rpg.StatisticInstanceSet'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.RuleSet'),
        ),
    ]
